### ISSUE TITLE
Documentation from Bourne

### ISSUE THREAD

**Issue by astroash** [TwinePlatform/hq#17]
A place to note documentation wanted from Bourne:

- [x] all up to date code pushed to github
- [x] setup guide for running dev environment locally
- [ ] guide for deploying production code
- [x] credentials for production database
- [x] credentials for deployment

_Feel free to add and amend as needed._

**Added**:
- [ ] guide for running tests (based on difficulties outlined in https://github.com/TwinePlatform/hq/blob/master/twine-admin-setup-guide.md)

**Comment by eliascodes** [comment]
Also guide for running tests!

**Comment by astroash** [comment]
When we have credentials for PHP deployment we can check whether we are able to have a single endpoint proxy for frontline to access statistical data:
https://github.com/TwinePlatform/twine-api/issues/32
